setup.py

Doing so fixes a 500 we were getting from Stitch due to "$ref"s not being resolved for "patternProperties" schemas. See https://github.com/singer-io/singer-python/pull/45
Testing
- A full sync of Jira into Stitch now works

singer-python 3.5.4

---

tap_jira/__init__.py
tap_jira/context.py
tap_jira/streams.py

The versions endpoint depends on the projects endpoint. So when projects are pulled, each project is fed into the version stream, which then pulls all the versions for that project. The way it had been written, if projects were selected, but versions were not, data for versions would still be pulled (they just wouldn't be written to stdout). This fixes that by getting versions to only pull data when necessary.
The flip side of this is that currently, if versions are selected, but projects are not, then no data will be synced. I assume this is undesired. If so let me know and I can fix.

Fix pulling versions data even when not selected

---

tap_jira/streams.py

Fix KeyError in case the `attachments` property is absent from the issue.

safety check attachments key before looping

---

tap_jira/schemas/changelogs.json
tap_jira/schemas/issue_comments.json
tap_jira/streams.py

Fixes a bug where, when a group of Issues were returned by a JIRA API query, only the changelogs for the last Issue were sync'd.  
Also adds the issueId field to changelogs so they can be linked to their parent Issue.  This was requested in [10](https://github.com/singer-io/tap-jira/issues/10)

Link changelog to issue

---

tap_jira/schemas/issue_transitions.json

#12 broke the tap - I had an old version of tap-jira installed in my virtualenv. Recreating the virtualenv and then running the tap caused it to fail. This change fixes the issue.

add json-type into schema for issue transitions

---

tap_jira/http.py

The startAt is an 0 based index value. Previously the code was returning issues multiple times and operating too slowly.

Use maxResults to set the startAt for the next page

---

tap_jira/context.py
tap_jira/streams.py

We've had some reports of missing data when using this tap consistently, this is an attempt to address an issue with how timezones are handled for the issues stream to avoid a possible cause.
The idea behind this is that the *Issues* stream requests using the `search` endpoint with JQL of `updated >= <bookmark_date>`. The problem here is twofold:
1. The `search` API, when queried by authorized users, uses the user's configured timezone to treat datetimes, [according to this Jira forum post](https://community.atlassian.com/t5/Jira-questions/JIRA-API-JQL-datetime-format-does-not-have-timezone/qaq-p/870844).
- So the bookmark that we're using is assumed by us to be in UTC, but Jira assumes it to be in, for example, "America/New_York".
2. The JQL parameter is just the ***date*** of the …

Adding timezone to Issues queries

---

.circleci/config.yml
tap_jira/http.py
tap_jira/streams.py

An API update broke the prior behavior because `%` was no longer being considered a wildcard. Our tests caught this. Fortunately there's a different endpoint that returns the same data.

use a different endpoint for users

---

tap_jira/streams.py

Search for users in all of the default groups described [here](https://confluence.atlassian.com/adminjiraserver/managing-groups-938847035.html), plus `users`, skipping any that don't exist.
Allow the list of groups to search to be overridden with the `groups` config parameter, specified as a CSV.

Configurable groups list

---

tap_jira/schemas/users.json

The endpoint as-is will not return these values. Syncing this data from Users would take a fundamental change in how the tap requests Users, so the fields are being removed.
This PR also updates the `users` schema to match the `UserDetails` object described under the `PageBeanUserDetails` response object in `Groups` -> `Get users from groups` [here](https://developer.atlassian.com/cloud/jira/platform/rest/v3/?utm_source=%2Fcloud%2Fjira%2Fplatform%2Frest%2F&utm_medium=302#api-rest-api-3-group-member-get)
**More Info**
The tap currently syncs users based on group using the `group/member` endpoint and values that are specified in the config, or a constant list [here](https://github.com/singer-io/tap-jira/blob/master/tap_jira/streams.py#L155-L159). According to the Jira API documentation, …

Removing groups and applicationRoles from users schema

---

tap_jira/streams.py
tests/spec.py

The tap currently uses a deprecated field as the `key_property` https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/#user.
This PR follows the migration guide to use `accountId` instead
- Ran syncs and confirmed that the target no longer complains
- 

Update key property for stream users

---

README.md

`user_agent` is required (by the tap) even when using Basic Auth.
(write a short description or paste a link to JIRA)
- 
- 

Document that user_agent is required in all modes

---

.circleci/config.yml
tests/base.py
tests/test_automatic_fields.py
tests/test_bookmarks.py
tests/test_custom_groups.py
tests/test_discovery.py
tests/test_full_replication.py
tests/test_pagination.py
tests/test_start_date.py

Rename duplicate test names, remove do_test pattern.
- 
- 

remove duplicate names, put create connection back in tests

---

tap_jira/__init__.py
tap_jira/context.py
tap_jira/http.py
tap_jira/streams.py
tests/unittests/test_error_handling.py

- Updated error handling of HTTP error and added Retry for error code 503.
- Check retry is working for 503.
- Instead of an error code proper message is coming now. 
- Other functionalities working as is.
- 

Tdl 14625 retry on 503 service unavailable

---

tap_jira/http.py
tests/unittests/test_basic_auth_in_discover.py

TDL-7575: Prevent connections that would yield a 401 from becoming fully_configured
- Added one API call for checking credentials validation.
- Verify that tap is raising an exception for status code 401 in discover mode and prevent fully configuration.
- 

TDL-7575: Prevent connection for 401 in check mode

---

README.md
tap_jira/http.py
tests/unittests/test_request_timeout.py

Added `request_timeout` to tap http client as per [TDL-16581](https://jira.talendforge.org/browse/TDL-16581)
- ran unit tests
- circle tests passing
- minimal

Add request timeout

---

tap_jira/__init__.py
tap_jira/http.py
tests/unittests/test_basic_auth_in_discover.py
tests/unittests/test_pk_switching.py

**TDL-14408 Investigate how to handle pk switching for on-prem vs cloud Jira**
- In the discover mode, we are checking the Jira instance type by making an API call.
- If an on-prem Jira instance is found, then we are updating the primary key of users as key
- For the cloud Jira instance, the primary key remains unchanged.
- 
- 

TDL-14408 Add pk switching logic for users stream

---

.circleci/config.yml
tap_jira/streams.py
tests/base.py
tests/spec.py
tests/test_all_fields.py
tests/test_automatic_fields.py
tests/test_bookmarks.py
tests/test_discovery.py
tests/test_pagination.py

TDL-17701: Add missing tap-tester tests
- Added `test_all_fields`
- Added missing assertions in discovery, automatic fields, and bookmark test.
NOTE: The test case is failing as the Primary Key is not unique for the `issue_transition` stream. [Asked in the community](https://community.atlassian.com/t5/Jira-questions/Issue-Transition-Primary-Key/qaq-p/1933996) for the same.
- 
- 

TDL-17701: Add missing tap-tester tests

---

setup.py
tap_jira/streams.py
tests/unittests/test_user_date.py

- Update `userStartDate` and `userReleaseDate` to `yyyy-mm-dd` format before transform.
- Added unittest cases to verify `transform_user_date` method.
- Update the language in the Jira profile setting to different European languages to verify the version stream.
- Run sync mode and verify that tap successfully transform records of version stream for any languages.
- 

TDL-18926 Transformation Issues

---

CHANGELOG.md
setup.py

Skipped record for out of range date : [#87](https://github.com/singer-io/tap-jira/pull/87)

bump version 2.1.5

---

tests/test_start_date.py

- Tap is already replication records inclusive of the start date for worklogs stream.
- In the start_date test case, a maximum of all bookmarks were being used as the start date for 2nd sync.
- Here, the maximum bookmark was `2022-02-24` and the last record of `worklogs` was for `2022-02-23`. That's why in the 2nd sync we were not getting any records of `worklogs`.
- Updated `start_date` test case to get records of all streams.
- 
- 

Tdl 19582 replication records inclusive of start date

---

tests/test_all_fields.py
tests/test_start_date.py

Get start date test fix from the PR below into master to avoid waiting for merge of Crest-master to master and allow daily builds to pass.
https://github.com/singer-io/tap-jira/pull/94
- 
- 

merge fix from PR 94 (Crest-master) to master
